# ========================================
# ServiceMonitor for Prometheus
# ========================================
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: auth-service-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: auth-service
  endpoints:
    - port: "8081"
      path: /actuator/prometheus
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: catalog-service-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: catalog-service
  endpoints:
    - port: "8082"
      path: /actuator/prometheus
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: schedule-service-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: schedule-service
  endpoints:
    - port: "8083"
      path: /actuator/prometheus
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: reservation-service-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: reservation-service
  endpoints:
    - port: "8084"
      path: /actuator/prometheus
      interval: 15s
